# fly.toml app configuration file generated for echo-crate-dawn-night-1411 on 2024-06-28T20:02:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echo-crate-dawn-night-1411'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
